### ISSUE TITLE
URL Update , Add Copy Button 

### ISSUE THREAD

**Issue by SikandarJODD** [Ianmello10/tiny-link#1]
Hey Can You do it : 
![image](https://github.com/Ianmello10/tiny-link/assets/93428946/b1b9c430-70e4-4293-93fd-00c77c2332ba)
also keep the redirect URL 
It will help users to check the URL and can even copy the URL

**Comment by Ianmello10** [comment]
Thanks for the suggestion, this has been added to the code

**Comment by Thedijje** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
jack97p, @eulis01, @unchang3d, @jakehemmerle, @miraclx, @mexican0001, @mkxml, @The34Goon, @sergiu128, @AntiqueBarbiex, @zy0n, @just-watch, @tomoguti, @stephen-a2z, @Liguratic, @Madjarx, @Loveisweird, @Sosyetekadir, @andrasfuchs, @josephgranata, @DavidAlphaFox, @connorstooks, @kingozorg, @ODAKAB, @Dimo99, @Libens-bufo, @darker0n, @aljones, @bageda, @sebasa, @jrgcubano, @modl21, @BTCparadigm, @bvolpato, @tetu14, @AritraBose10, @Qubit08, @ryosukeeeeee, @gallypette, @ktalich, @joemccann, @ycaedes, @Energy0124, @naoki-maeda, @stone9988, @digitalvirtuallife, @merlinepedra, @tianshanghong, @hjco, @subha-afk

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Fjlehner, @sketch34, @s10s-btc, @fz420, @QuixoteSystems, @MrJohnsson77, @LawrenceLN, @nilnu1l, @Mjoly1024, @zoidbergZA, @fosscat, @rodant, @RohanKapurDEV, @Ziya-Sadr, @orlin, @StarHunter58, @yijun-lee, @ryjen, @GAlcaraz, @mbelletti, @mysticaltech, @jadsonlourenco, @adshao, @radoystoyanov, @enorrmann, @melvincarvalho, @soheilsh7, @stewarthu, @Satoshi55, @matthewbotti, @nochiel, @moma4211, @kevATin, @PraiaBitcoin, @arkin0x, @LightningK0ala, @lackrobin, @alouldz, @nicklyk, @ldipenti, @Sandalots, @badonyx, @axon4, @Jeezman, @vieirapedro, @DjamsNoddier, @Cuchulain, @ngoluuduythai, @oldmonad, @leitaomd
